### ISSUE TITLE
reorganise modules to avoid conflicts

### ISSUE THREAD

**Issue by Guria** [ashercn97/funsies#2]
https://discord.com/channels/768594524158427167/1281967484731265044

Your package uses cli, db, templates namespaces which can lead to a conflicts with a really high chance.

**Comment by ashercn97** [comment]
Oh! This is super good to know, thanks! I will fix it right now.

I am new to Gleam, so there are tons of things that I don't know. Thank you!

**Comment by Guria** [comment]
Make sure to join Discord :)
Creator of Gleam not a fan of ORMs, but I am pretty sure you will still get some help and support there.

**Comment by ashercn97** [comment]
I didnt even realize there was a discord haha! Thank you. And yeah, I feel like a lot of people don't like ORMs. Then again, maybe ORM isn't the right word for whatever this project is.

I wanted to build it cuz I loved Ecto in the Phoenix/Elixir ecosystem. I'm not sure whether Ecto even counts as an ORM. So maybe this is more of an in-between-ies. I will have to see where it goes.

**Comment by ashercn97** [comment]
Okay, hopefully this is better.

I moved cli to cli_project, db to the name of the project (funsies), and templates to builders. Those are less common?

**Comment by Guria** [comment]
@ashercn97 It become less chance to have the conflict, but it still not 0. Consider putting everything under package name namespace

**Comment by ashercn97** [comment]
@Guria  I don't follow. How would I do that? Like, define everything under just the `funsies` folder? Or all in the funsies file? Are there any examples you can point me to?

**Comment by ashercn97** [comment]
I JUST realized what you meant. Sorry, I don't know why it took me so long. On it!
